CREATE DATABASE biscoito;

USE biscoito;

CREATE TABLE usuario (
CPF BIGINT NOT NULL,
NomeUsuario VARCHAR(60) NOT NULL,
SobrenomeUsuario VARCHAR(80) NOT NULL,
Email VARCHAR(60) NOT NULL,
Senha VARCHAR(12) NOT NULL, 
DataNascimento DATE NOT NULL,
Sexo CHAR(1) NOT NULL,
PRIMARY KEY (CPF) 
);

CREATE TABLE endereco(
Endereco INT(11) NOT NULL,
CPF BIGINT NOT NULL,
Logadouro VARCHAR(60) NOT NULL,
numero VARCHAR(7) NOT NULL,
Complemento VARCHAR(60) NOT NULL,
Bairo VARCHAR(60) NOT NULL,
Cidade VARCHAR(60) NOT NULL,
Cep VARCHAR(60) NOT NULL,
PRIMARY KEY (Endereco),
FOREIGN KEY (CPF) REFERENCES usuario(CPF) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE categoria(
IdCategoria INT NOT NULL AUTO_INCREMENT,
Descricao VARCHAR(50) NOT NULL,
PRIMARY KEY (IdCategoria)
);

CREATE TABLE produto(
IdProduto INT(11) NOT NULL AUTO_INCREMENT,
IdCategoria INT NOT NULL,
NomeProduto VARCHAR(30) NOT NULL,
Descricao VARCHAR(60) NOT NULL,
Preco DOUBLE NOT NULL,
PRIMARY KEY (IdProduto),
FOREIGN KEY (IdCategoria) REFERENCES categoria(IdCategoria) ON DELETE CASCADE ON UPDATE CASCADE
);
